name: CI_dotnet_build_&_test

on: [pull_request, push] 

jobs:
  postman:
    runs-on: [windows-latest]
    
    steps:
    
    - name: Install Postman CLI
      run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
        
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      
    - name: Run API tests
      run: |
        postman collection run "29793772-2a57d778-ecda-4928-bc3c-d3d807cf8b01"
        
  dotnet:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Show Dir
      run: ls
      
    - name: Build
      run: dotnet build ./PlatformService/PlatformService.sln
      
    - name: Run
      working-directory: PlatformService/PlatformService
      run: dotnet run . --no-build --verbosity normal
      

