name: Build Docker Container


on: push
jobs:
    build-container:
      name: Build container
      runs-on: ubuntu-latest
      steps:
      - name: Checout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Show Dir
        run: ls

      - name: Build Dockerfile
        run: docker build ./PlatformService --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/4_semester:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/4_semester:latest
